require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - "app/assets/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "db/*"
    - "public/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false